# Generated by Django 5.0.1 on 2024-01-22 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("executor", "0001_initial"),
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="task",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="task.task"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="member",
            field=models.ManyToManyField(
                related_name="teams", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="task",
            field=models.ManyToManyField(related_name="teams", to="task.task"),
        ),
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="executor.team",
            ),
        ),
    ]
