# Generated by Django 5.0.1 on 2024-01-15 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0003_alter_worker_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("deadline",)},
        ),
    ]
