# Generated by Django 5.0.1 on 2024-01-16 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0006_alter_tag_options_team_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="member",
        ),
        migrations.RemoveField(
            model_name="team",
            name="task",
        ),
        migrations.AddField(
            model_name="team",
            name="member",
            field=models.ManyToManyField(
                related_name="teams", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="task",
            field=models.ManyToManyField(related_name="teams", to="task_manager.task"),
        ),
    ]
