# Generated by Django 5.0.1 on 2024-01-17 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0008_alter_project_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="task_manager.team",
            ),
        ),
    ]
