# Generated by Django 5.0.1 on 2024-01-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0009_alter_project_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
